sudo: required
language: generic
dist: trusty

matrix:
  include:
  - name: "Kinetic"
    env: ROS_DISTRO=kinetic BEFORE_SCRIPT="sudo -H pip install --upgrade pip && hash -r pip"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
